AWSTemplateFormatVersion: '2010-09-09'
Description: AI Assistant Platform - Cognito User Pool

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues: [dev, hml, prd]

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ai-assistant-platform-${Stage}
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      MfaConfiguration: 'OFF'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - Name: tenantId
          Mutable: true
          AttributeDataType: String
          StringAttributeConstraints:
            MaxLength: '64'
        - Name: role
          Mutable: true
          AttributeDataType: String
          StringAttributeConstraints:
            MaxLength: '20'
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ai-assistant-platform-client-${Stage}
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      PreventUserExistenceErrors: ENABLED
      WriteAttributes:
        - email
        - custom:tenantId
        - custom:role
      ReadAttributes:
        - email
        - custom:tenantId
        - custom:role

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: !Sub ai-assistant-platform-user-pool-id-${Stage}
  UserPoolArn:
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub ai-assistant-platform-user-pool-arn-${Stage}
  UserPoolClientId:
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub ai-assistant-platform-user-pool-client-id-${Stage}

