AWSTemplateFormatVersion: '2010-09-09'
Description: AI Assistant Platform - S3 Buckets

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues: [dev, hml, prd]

Resources:
  KnowledgeBaseBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ai-assistant-platform-kb-${Stage}-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Stage
        - Key: Project
          Value: ai-assistant-platform

  ConversationLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ai-assistant-platform-logs-${Stage}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
          - Id: ExpireOldLogs
            Status: Enabled
            ExpirationInDays: 90
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Stage
        - Key: Project
          Value: ai-assistant-platform

Outputs:
  KnowledgeBaseBucketName:
    Value: !Ref KnowledgeBaseBucket
    Export:
      Name: !Sub ai-assistant-platform-kb-bucket-${Stage}
  ConversationLogsBucketName:
    Value: !Ref ConversationLogsBucket
    Export:
      Name: !Sub ai-assistant-platform-logs-bucket-${Stage}

